### PR TITLE
Disable multiprocessing on darwin systems

### PR DESCRIPTION
**Pull request by haykh**
Temporarily solves #323

### CODE REVIEW

**Comment by alejandrogallo** [comment]
Hy @haykh, 
thank you for your pull request. I am not sure this is the way to go that some macos user will not be able to use
parmap, but it is a little bit hard to decide as I do not use macOS. Maybe @avonmoll can comment on this request.
According to your last comment on the #323 thread you said that the overhead for the thread creation
was almost unnoticeable, at least as far as I can see, is this fixing this minimal overhead?

Anyways I have no problem merging this for the time being, but I'd like to be sure that it is for this minimal overhead.
In this case I'd ask from you to add a TODO comment with the link to the #323 request for future reference.
thanks!

**Comment by avonmoll** [comment]
It's a big plus for me because I'm essentially already using it this way and can now update safely without overwriting the 'patch' from #323. For general mac users it's hard to say since I don't have access to a machine for which the multi-processing stuff worked fine on (for pythons >3.6). The only thing I can say is that papis _feels_ snappy for me now (with nearly 500 docs) and I imagine the user experience will still be decent for the average mac user.

**Comment by alejandrogallo** [comment]
Ok, that sounds reasonable. I'll merge it, @haykh could you add the `TODO` notice on the line after the `if`?

**Comment by haykh** [comment]
@alejandrogallo the overhead is minor but noticeable. Since the whole purpose of multiprocessing is to boost performance I thought it sort of defies that idea. I added a todo comment for the future, but, yes, like @avonmoll says, it never worked for me on python past v3.6/3.8. I'll give this a more proper look when I have a bit more time.

**Comment by alejandrogallo** [comment]
Brilliant, thank you very much!

**Pull request merged**
