### PR TITLE
Ci flake update

### LINKED ISSUE #733: Nix CI is taking a very long time
It seems like the nix CI started taking forever for a few weeks now (up to 45-ish minutes from 3-ish minutes). Last run this Friday (January 26) that took 45 minutes
https://github.com/papis/papis/actions/runs/7671144689
and the last run that worked (January 5) and took 2 minutes
https://github.com/papis/papis/actions/runs/7424640365

@f0rki Any idea what could be wrong there? I haven't really had time to investigate..

### PR DESCRIPTION
**Pull request by f0rki**
Sorry for the slow response time. Updated the nix flake and the CI to conform to nix/CI best practices (i.e., maximum caching).

Fixes #733

### CODE REVIEW

**Comment by f0rki** [comment]
Caveat: one has to update the `flake.lock` file regularly now. Need to find out whether there is automation to do that.

**Comment by alexfikl** [comment]
Thanks a lot for helping with this! Is there any documentation for how to set this up? I googled around a bit and was pretty unsuccessful :(

> Caveat: one has to update the `flake.lock` file regularly now. Need to find out whether there is automation to do that.

For now maybe you can add a target to the `Makefile` so that anybody can run a `make flake.lock` and update that file?

**Comment by f0rki** [comment]
Good point, it is just `nix flake update`.

**Comment by alexfikl** [comment]
Thanks again! In it goes :rocket:

**Pull request merged**
