### PR TITLE
ref-format: use dynamically

### PR DESCRIPTION
**Pull request by teto**
I would like to change the ref according to ref-format dynamically rather than on import
see https://github.com/papis/papis/issues/141.

For the behavior, I wonder what to do if it can't generate the ref : fallback on a ref if it exists but otherwise ? use a default key "unknown" ?
```
Using ref-format = {doc[author_list][0][surname]}{doc[year]}
on <papis.document.Document object at 0x7f2abbe9d0b8>
Traceback (most recent call last):
  File "/run/user/1000/tmp.6p8bvkMjc8/bin/papis", line 11, in <module>
    load_entry_point('papis', 'console_scripts', 'papis')()
  File "/home/teto/papis/papis/main.py", line 10, in main
    papis.commands.default.run()
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teto/papis/papis/commands/export.py", line 195, in cli
    text=text
  File "/home/teto/papis/papis/commands/export.py", line 100, in run
    papis.document.to_bibtex(document) for document in documents
  File "/home/teto/papis/papis/commands/export.py", line 100, in <listcomp>
    papis.document.to_bibtex(document) for document in documents
  File "/home/teto/papis/papis/document.py", line 122, in to_bibtex
    document
  File "/home/teto/papis/papis/utils.py", line 94, in format_doc
    return python_format.format(**{doc: document})
IndexError: string index out of range
```

### CODE REVIEW

**Comment by alejandrogallo** [comment]
Hi @teto,

I would propose the following pseudo code

```python
if document.has('ref'):
    ref = document['ref']
elif papis.config.get('ref-format'):
    # Construct your reference
elif document.has('doi'):
    ref = document['doi']
else:
    ref = # folder name of the document
```

What do you think?

**Comment by teto** [comment]
I think it makes sense if the ref building is adjusted. I assume the yaml always gets generated with a ref but if it can't generate a ref, it should leave it empty instead of "noreference". In the short run, I would like to fix 
https://github.com/papis/papis/pull/150 first.

**Comment by teto** [comment]
@alejandrogallo so I fixed the ref generation to match your logic (which I agree with). I wonder if that should go into its own function. 
I plan to write a test (and clean up the code). Is there a database of document or some specific test I could inspire myself from ?

As for the zotero-sql part, I wonder if it would be fine to pass the sqlite database instead of just the folder and assume that the database is named "zotero.sqlite". It would allow to let argparse check/open for the file and might be more robust in case some people renamed it ( like I did to zotero-backuup.sqlite). That would be a separate PR.

**Comment by alejandrogallo** [comment]
Hi! Thank you very much for everything.
I merged it with the exception for commit abdf875
since the `--all` flag in export just means that you export all the selected documents with the query.
If you want to export everything with whoosh, the logic is
```
papis export --bibtex --all '*'
```

we can discuss the logic..

**Comment by teto** [comment]
haaa you merged before I had time to cleanup xD ! I will add tags [WIP] / [READY] next time :p 

`papis export --bibtex --all '*'` works but `papis export --bibtex --all` won't. I think it doesn't use `default-query-string = '*'` as for open so that's confusing.

What about `As for the zotero-sql part, I wonder if it would be fine to pass the sqlite database instead of just the folder and assume that the database is named "zotero.sqlite".` ?

**Pull request closed without merging**
