### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by alexfikl**
@alejandrogallo @jghauser I went through the pull requests and added them to the CHANGELOG file with a bit of details. What do you think?

You can see it rendered here
https://github.com/alexfikl/papis/blob/update-changelog/CHANGELOG.md

There's probably some missing parts, so I'm not sure how to best handle this. Should we just merge the PR and update it later or keep it open and add to it until the release?

### CODE REVIEW

**Comment by jghauser** [comment]
Thanks for this (and all the other work you've been doing)! It looks very neat to me. I don't have any preferences either way, though I do think it would make sense to have a release soon, seeing that there are so many improvements in papis!

**Comment by alejandrogallo** [comment]
Wow this is a great changelog! Are there some missing parts? I can't right now think of anything. I'd have to go through the commit titles to take a look.
Nevertheless I think the major changes are already in the changelog which is great.

I also think it's time to create a new release, long overdue.
I just have to change the default vi mode in the notes editor in the webapp, I realised that testing it I left it there, and maybe if you think of something else to do before releasing I can do it tomorrow ?

**Comment by alejandrogallo** [comment]
Also the FOSDEM video is already online, 

https://fosdem.org/2023/schedule/event/openresearch_papis/

I guess we could put it somewhere in the documentation, although I don't know if
this video will rather scare people off ;D

**Comment by alexfikl** [comment]
> Wow this is a great changelog! 

Thank you! :heart: 

> Are there some missing parts? I can't right now think of anything. I'd have to go through the commit titles to take a look. Nevertheless I think the major changes are already in the changelog which is great.

I was mostly thinking if there were any parts in the webapp, citations command, etc that you'd like to highlight more (I just skimmed the commits and added some stuff there). There might be some other smaller changes / fixes missing, but that's no biggie.

> I also think it's time to create a new release, long overdue. I just have to change the default vi mode in the notes editor in the webapp, I realised that testing it I left it there, and maybe if you think of something else to do before releasing I can do it tomorrow?

There are some pull requests still open, but nothing big or urgent in any way. Maybe your #467 should go in? That seems like an annoying bug for bibtex. I managed to add some conflicts to that, but from what I remember it was otherwise good to go :rocket: 

So yeah, I'm also very much in favor of doing a release! It's been a while :tada:

**Comment by jghauser** [comment]
I think there might also be a bug introduced by my beautification effort. At least on my system when I try to add an doc that already exists, there's some decidedly unpretty python error trace. Haven't had the time to investigate yet, but I think we should fix that before the release.

**Comment by alexfikl** [comment]
> I think there might also be a bug introduced by my beautification effort. At least on my system when I try to add an doc that already exists, there's some decidedly unpretty python error trace. Haven't had the time to investigate yet, but I think we should fix that before the release.

When you find some time, can you share the error? I just tried adding a document that exists and couldn't seem to get a traceback.

**Pull request merged**
