### PR TITLE
jinja2: remove support

### PR DESCRIPTION
**Pull request by teto**
It makes little sense to have a separate path specifically for jinja2.
Same behavior should be achievable via plugins.

### CODE REVIEW

**Comment by alejandrogallo** [comment]
I agree, it looks fine, let us remove it for version 0.9, only @avonmoll is really using it to my knowledge, so we can develop other plugins for coming versions as you point out. This pr is a go for me.

**Comment by teto** [comment]
@avonmoll do you have a backup plan if I merge this or should I wait ?

**Comment by avonmoll** [comment]
I would say go ahead and merge. I'm currently using a version of 0.9 from a month or so ago with all of my PRs merged in. I would like to better understand how to achieve finer control over the templates (filenames, ref formats, etc.). In my naive mind, there would be some way to hook in a plugin or even just a single script that gets called when papis needs to generate a filename or refformat. Right now, we can only specify a textual template in the config. Without jinja2, there is much less control over how these are generated.

My use case is using papis as a master repository, tagging various documents (using the `project` list field) for a particular paper, then exporting all documents with `project:newPaper` to bibtex. When writing LaTeX documents I'd like to avoid the scenario where the cite keys are ambiguous or uninformative (e.g. `johnson2015the` or `johnson2015a`). A lot of times, I cite multiple works from the same author in the same year. It gets confusing sometimes (even now, with what's possible in jinja2). I don't know if this helps to explain why I want more control over things like ref format.

**Comment by teto** [comment]
We should have a flag to either prevent duplicate keys (by adding a counter for instance) or warn the user.
As for more control over the format, the current system looks powerful enough, apart from the duplicate problem. What I do is that I add the reference manually in info.yaml, then they are not generated. Have you tried that ?
Can't you just manually ed

**Comment by avonmoll** [comment]
Manually editing the `refformat` field is always an option. It's much more annoying for things like file and folder names though. My concern is less with duplicate keys (although that should be avoided somehow) and more with `refformat`s with stop-words like "a" or "the". This has nothing to do with jinja2 (as it's not possible there either). This is what prompted my original interest in being able to call a script to generate names. I don't think it should be a high priority since the current naming template configurations are probably sufficient for the vast majority of users.

**Comment by teto** [comment]
I think editing the info.yaml with `ref: BertotYves2015` is a good solution.
As for ref-format and your ambiguous example `johnson2015the` vs `johnson2015a`, setting ref-format to use the title should fix the ambiguity ?

**Comment by alejandrogallo** [comment]
Can I merge this?

**Comment by teto** [comment]
yes go ahead please.

**Pull request merged**
