### PR TITLE
link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello!

The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).

Cheers :-)

### CODE REVIEW

**Comment by alejandrogallo** [comment]
Hi Katrin, thanks so much!
Cheers!

**Comment by katrinleinweber** [comment]
You're welcome :-)

**Comment by katrinleinweber** [comment]
PS: Does the function docu need changing as well? https://github.com/papis/papis/blob/f8f57cc30b8885b24d5f5804578458bb7f548308/papis/crossref.py#L408-L410

**Comment by alejandrogallo** [comment]
That's right, you cann add a doctest if you want without the dx, but leave the dx test also in place.
Thanks again!

**Pull request merged**
