### PR TITLE
docs(merge): resolve TODO and add examples

### PR DESCRIPTION
**Pull request by kiike**
I'm going through the TODOs scattered around the code, so I can learn more about the papis code.

I found a documentation TODO and I think i managed to resolve it.

It's my first doc here so let me know if it's alright. I checked it in browser and it doesn't look bad.

### CODE REVIEW

**Comment by alexfikl** [comment]
Very nice! I've never actually used `papis merge`. Does it work? :grin:

**Comment by kiike** [comment]
> Very nice! I've never actually used `papis merge`. Does it work? 😁

Neither did I, but I do have a lot of duplicates so stumbling upon this TODO and writing this was a good experience!

It works fine! It can merge two entries at the same time and not more, but that is alright. I had a document that was duplicated three times, so I just ran it twice.

**Comment by jghauser** [comment]
Looks great, thanks! I'd maybe capitalise "Papis", though admittedly we've not been super consistent with it...

**Comment by kiike** [comment]
I saw it in lowercase in `add.py`, which I was using as a reference :yum:. I'll capitalize it here and make a different pull request to uppercase all other references.

**Comment by kiike** [comment]
Oh, even the same file has it in lowercase, just above examples :laughing: 

So, is uppercase the "right way"?

**Comment by jghauser** [comment]
> So, is uppercase the "right way"?

Good question! I've been using "Papis" and changing things when I encountered other ways of writing it (hence, it's what's used in the README). What do you think @alexfikl?

**Comment by kiike** [comment]
> > So, is uppercase the "right way"?
> 
> Good question! I've been using "Papis" and changing things when I encountered other ways of writing it (hence, it's what's used in the README). What do you think @alexfikl?
> 
> EDIT: In any case, at the beginning of sentences, I think lower case looks a bit odd.

Not if it's a command, IMHO.

Anyway I searched old versions of the code and it looks like the project name is Papis, not papis.

https://github.com/papis/papis/commit/96ce070197ab7af7c043c0aa0a0c1bfc10310df8

**Comment by kiike** [comment]
Capitalised Papis in https://github.com/papis/papis/pull/793/commits/158d0416ae5e01e3404787955094bce591074911, advise if I should revert it. Thanks for giving feedback so quickly!

**Comment by jghauser** [comment]
I think consistency is what matters most here and if we can have history help us decide, all the better! And thanks for digging up this old commit, interesting to see how far Papis has come :blush:

**Comment by alexfikl** [comment]
> Good question! I've been using "Papis" and changing things when I encountered other ways of writing it (hence, it's what's used in the README). What do you think @alexfikl?

I've been doing the same (possibly inspired by some of your documentation changes), so definitely :+1: for having it capitalized.

**Pull request merged**
