### PR TITLE
docs: rewrite quickstart+overview+sample workflow

### PR DESCRIPTION
**Pull request by kiike**
Very early draft, just to track progress.

My aim for now is to help fix part of #413, #825 #328 #304 for the parts concerning what you do with Papis right after installing it.

### CODE REVIEW

**Comment by alexfikl** [comment]
That's a very large chunk of changes. My recommendation would be to split it up into smaller PRs: would be easier to review and more likely to get some stuff in if you run out of steam before finishing everything up.

**Comment by kiike** [comment]
Oh i completely miswrote my intentions. What I'd like in this PR is to work on the quickstart/sample workflow/overview issues. So, give a birds-eye view of what you can do with Papis. Hopefully trying to imply why you would want to use this instead of, say, Zotero.  Refactoring the whole documentation is very unlikely because of the huge scope.

**Comment by alexfikl** [comment]
> Oh i completely miswrote my intentions. What I'd like in this PR is to work on the quickstart/sample workflow/overview issues. So, give a birds-eye view of what you can do with Papis. Hopefully trying to imply why you would want to use this instead of, say, Zotero. Refactoring the whole documentation is very unlikely because of the huge scope.

Haha, nevermind then, carry on! I just saw "docs: rewrite" and panicked a bit :grin:

**Comment by kiike** [comment]
> > Oh i completely miswrote my intentions. What I'd like in this PR is to work on the quickstart/sample workflow/overview issues. So, give a birds-eye view of what you can do with Papis. Hopefully trying to imply why you would want to use this instead of, say, Zotero. Refactoring the whole documentation is very unlikely because of the huge scope.
> 
> Haha, nevermind then, that sounds good! I just saw "docs: rewrite" and panicked a bit 😁

Fair enough! :laughing:

**Comment by kiike** [comment]
Since the users that would eventually use papis are already somewhat familiar with the command line, I skipped speaking of so common command-line patterns. Like define what a flag is.  Same with define what a commands or subcommands is, or what `~` in a path means.  I mean, if you install papis, except for the Windows installer, you'll know at least the basics of the command line.

Now for this changes, I'd like to know what you think of my edits. I'm not the best writer but I think I could manage to walk through some first steps of using Papis right after installation.

I'd love it if you had a read (@alexfikl, @jghauser) and tell me how you like it. I think for the quickstart I would like to aim for not mentioning the `info.yaml` nitty-gritty and focus on using the `papis` command, then mention the library structure and `info.yaml` in other sections. Do you agree? 

I also added a rudimentary workflow.  It is based on what I use. Maybe other people would use Obsidian or something like that but, for me, I like to collect all the info in notes, then sort them, and dump them into a raw file that I will use for actually writing out my deliverables.

**Comment by alexfikl** [comment]
> Since the users that would eventually use papis are already somewhat familiar with the command line, I skipped speaking of so common command-line patterns. Like define what a flag is. Same with define what a commands or subcommands is, or what `~` in a path means. I mean, if you install papis, except for the Windows installer, you'll know at least the basics of the command line.

Agreed! We already assume that users know about the command line and git and stuff like that in most of the docs (either with the terminology or with the references). My general thought is that less geeky users can go for the webapp or some other interface that's more friendly in that regard.

**Comment by kiike** [comment]
> > Since the users that would eventually use papis are already somewhat familiar with the command line, I skipped speaking of so common command-line patterns. Like define what a flag is. Same with define what a commands or subcommands is, or what `~` in a path means. I mean, if you install papis, except for the Windows installer, you'll know at least the basics of the command line.
> 
> Agreed! We already assume that users know about the command line and git and stuff like that in most of the docs (either with the terminology or with the references). My general thought is that less geeky users can go for the webapp or some other interface that's more friendly in that regard.

Nice! Looking forward to feedback on the other aspects :grin:

**Comment by jghauser** [comment]
This is great, thanks a lot for working on this! From a quick glance, this is a big improvement! :heart:

I'm gonna have a look over the next days! Before I do, I wanted to ask if you're ok with me freely editing and changing things (and just pushing the edits to this branch or adding one big suggestion in the review). It tends to be the quickest for prose, but I don't want to just take over. If you'd prefer that I leave some comments about possible improvements instead that is totally ok with me! Let me know :relaxed:

**Comment by kiike** [comment]
Thanks for having a look at it @jghauser! Oh i'd be so grateful if we were doing this more collaboratively! I haven't been using Papis for long, so there might be something I am missing. Also, regarding form, that writing is as messy as my thoughts :smile:. So yes, feel free to change things here! When you get bored, I can take over too! We can also do it together in an etherpad/googledocs realtime! I'm usually available on evenings 9PM-1AM european time.

**Comment by jghauser** [comment]
I think doing this on an etherpad could speed things up -- great idea! I'm quite busy these days (or rather unpredictably busy haha), so I'm not sure if I'll manage to find a set time before the end of the month, but even for asynchronous editing, it should have a fair bit less friction than github (and we wouldn't have to worry about creating clashes). Feel free to start a pad if you want :).

**Comment by kiike** [comment]
https://pad.riseup.net/p/CXG7ZX33R0hHeYbtjndh << hit me up when you work on it and i'll join if I'm around

**Comment by jghauser** [comment]
Ok, finally had a first quick read through it and wrote some initial comments. let me know what u think (no need to implement anything yet). i've missed the commenting functionality, so i've opened another pad on framapad: https://semestriel.framapad.org/p/72su9jeso6-a7hm?lang=en

**Comment by kiike** [comment]
Good! Thanks for the comments. I replied to them!

**Comment by jghauser** [comment]
sorry for being so slow on this! but i have started editing the text and should get to the rest of it later this week. let me know what you think. i've left some new comments as well if you want to have a look

**Comment by jghauser** [comment]
did a little more work, if you want to take a look @kiike :relaxed:

**Comment by kiike** [comment]
> did a little more work, if you want to take a look @kiike ☺️

Nice changes. Your style definitely makes it more friendly for a newcomer.

**Comment by jghauser** [comment]
Nice to hear! :blush: It's quite enjoyable to improve things in this way given that you've done so much of the content heavy-lifting!

**Comment by jghauser** [comment]
Does anyone know the default location for the config on macOS, according to #745 it's at `~/Library/Application Support/$appname/$version`, but what does that mean in practice? I asssume `$appname` is `papis`, but what is version? Does that change every time we update Papis?

PS: I'm almost done with it! Need to take a second look at the "Organizing your library's folders" section and then go over the whole thing once more and we're good!

**Comment by alexfikl** [comment]
> Does anyone know the default location for the config on macOS, according to #745 it's at `~/Library/Application Support/$appname/$version`, but what does that mean in practice? I asssume `$appname` is `papis`, but what is version? Does that change every time we update Papis?

It should be just `~/Library/Application Support/papis`. We don't set the version when calling `platformdirs`, so it shouldn't use that.

**Comment by jghauser** [comment]
Perfect, thanks @alexfikl!

**Comment by jghauser** [comment]
Ok, this is mostly done now. If you have time, feel free to take a look @kiike, @alexfikl. You can ignore all the comments, as I've resolved all these issues (except one about a link, where I'm unsure about the syntax).

**Comment by alexfikl** [comment]
> Ok, this is mostly done now. If you have time, feel free to take a look @kiike, @alexfikl. You can ignore all the comments, as I've resolved all these issues (except one about a link, where I'm unsure about the syntax).

Is this where the latest version is: semestriel.framapad.org/p/72su9jeso6-a7hm?lang=en?

**Comment by jghauser** [comment]
> Is this where the latest version is: [semestriel.framapad.org/p/72su9jeso6-a7hm?lang=en](semestriel.framapad.org/p/72su9jeso6-a7hm?lang=en)?

Yes!

**Comment by kiike** [comment]
A very nice improvement overall! There's that paragraph with off grammar that Alex already gave feedback for. I've corrected some typos, but I like your changes @jghauser!

**Comment by jghauser** [comment]
> Two bigger remarks:
> 
>    - We currently make a distinction between `importers` and `downloaders`. The main difference is that importers can be used with `papis add --from IMPORTER URI` while downloaders are called when you just do `papis add URI`. Ideologically, downloaders are also more for scraping websites, while importers are for some more established APIs.

Oh, thanks a lot! I actually got confused by [a passage in our docs](https://papis.readthedocs.io/en/latest/plugins.html#importer) which said that "The difference between a downloader and an importer is largely semantic" (which, as a philosopher, I find a problematic description, but that's another topic :sweat_smile:). I assumed that this means that downloaders download from the web and importers get stuff from somewhere local -- I hadn't realised they are employed differently as well. Thanks!

>    - There are some rst vs markdown formatting issues in there. We'll probably notice those better when the document gets copied back into `quick_start.rst`.

Yeah, I'm sure there are ugh. It's hard to switch back and forth when about equally many things are the same as are different between the two formats. On another note, I would really quite like if we used markdown for everything. I've looked into it, and it doesn't seem all that straightforward unfortunately...

**Comment by alexfikl** [comment]
> Oh, thanks a lot! I actually got confused by [a passage in our docs](https://papis.readthedocs.io/en/latest/plugins.html#importer) which said that "The difference between a downloader and an importer is largely semantic" (which, as a philosopher, I find a problematic description, but that's another topic 😅). I assumed that this means that downloaders download from the web and importers get stuff from somewhere local -- I hadn't realised they are employed differently as well. Thanks!

Haha, I think I wrote that part at some point and mostly thought "they both add things to the library, whatever". But yeah, they also have some actual practical differences which we should make clearer at some point.

> Yeah, I'm sure there are ugh. It's hard to switch back and forth when about equally many things are the same as are different between the two formats. On another note, I would really quite like if we used markdown for everything. I've looked into it, and it doesn't seem all that straightforward unfortunately...

Yeah, that's a pretty big job because we have a pretty large amount of guides and docs and things. One option we can go for is using the [MyST](https://myst-parser.readthedocs.io/en/latest/) parser for Sphinx, which seems to allow both markdown and rST, making the transition more gradual.

Personally I'm not very bothered either way because most python projects I contribute to use Sphinx with rST, so I'm not getting away from it :(

**Comment by jghauser** [comment]
Grr, is it really not possible to use markup for linked text? I'm trying to do something like

```
`:ref:```add-folder-name`` configuration option <general-settings:add-folder-name>`
```
I'm hoping to get `add-folder-name` <- like this. But it gets me the following:
2024-05-21T19:31:15,336994457+02:00

 [This discussion](https://stackoverflow.com/questions/4743845/format-text-in-a-link-in-restructuredtext) seems to indicate it's not possible without some very ugly shenanigans. @alexfikl, do you have any idea how to do this (easily)?

**Comment by alexfikl** [comment]
> Grr, is it really not possible to use markup for linked text? I'm trying to do something like

We have a special role for configuration options. Something like `` :confval:`add-folder-name` `` should show up very similarly to a double backtick and link to the correct configuration value. Is that what you had in mind?

**Comment by jghauser** [comment]
> > 
> 
> We have a special role for configuration options. Something like `` :confval:`add-folder-name` `` should show up very similarly to a double backtick and link to the correct configuration value. Is that what you had in mind?

Ah, that's much easier! Perfect! :heart:

**Comment by jghauser** [comment]
Ok, once the CI is done, I think this can be merged. I did also fix #861 and move the database structure info in the docs (I didn't think that fit into the intro part). If we want a neater commit history we might want to rejiggle the commit history a bit first.

**Comment by alexfikl** [comment]
> Ok, once the CI is done, I think this can be merged.

Looks good to me too! @kiike Feel free to un-draft this and we can merge it whenever you're ready too! :rocket: 

> I did also fix #861 and move the database structure info in the docs (I didn't think that fit into the intro part). If we want a neater commit history we might want to rejiggle the commit history a bit first.

The commits are pretty clean, so it should be ok to just merge it :shrug:

**Comment by jghauser** [comment]
Small question: I had to split two of the cli commands over two lines with ``\``. Is this even supported on Windows? Also, I'm using wget in two places, that might also not work so well on Windows (and macOS)?

**Comment by alexfikl** [comment]
> Also, I'm using wget in two places, that might also not work so well on Windows (and macOS)?

I think macOS comes with `curl` but not `wget`, so maybe we can use that instead?

**Comment by jghauser** [comment]
> I think macOS comes with `curl` but not `wget`, so maybe we can use that instead?
> 
> EDIT: Seems like Windows may also have curl: https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

Ok, let's use curl then!

**Comment by kiike** [comment]
> hey @kiike, just a gentle reminder in case this has fallen off your radar. are you happy with the state of this? it would be nice to merge if it is all done :)

I am more than happy with the state of this! I think the changes you made will help a lot the newcomers to Papis. Good job!

**Comment by jghauser** [comment]
> > hey @kiike, just a gentle reminder in case this has fallen off your radar. are you happy with the state of this? it would be nice to merge if it is all done :)
> 
> I am more than happy with the state of this! I think the changes you made will help a lot the newcomers to Papis. Good job!

Great, good to hear! I'll merge it then :heart:

**Pull request merged**
