### PR TITLE
test: add pytest marker for git executable

### LINKED ISSUE #944: Feature request: Mark tests that need git so they can be disabled on non-git setups
* papis version (`$ papis --version` or commit number): 0.14

# how to reproduce the issue
On a system where `git` isn't installed (for example, a clean chroot on a build system containing the minimal `papis` dependencies), the following tests fail due to its absence
```
FAILED tests/commands/test_git.py::test_git_cli - FileNotFoundError: Command ...
ERROR tests/commands/test_add.py::test_add_run - FileNotFoundError: Command n...
ERROR tests/commands/test_rm.py::test_rm_files_run - FileNotFoundError: Comma...
```

Alternatively, please document that `git` is required to be installed.

### PR DESCRIPTION
**Pull request by alexfikl**
Fixes #944

### CODE REVIEW

**Comment by hseg** [comment]
You're faster than me -- I was just writing up a PR of my own that would've used
```python
needsGit = pytest.mark.skipif(
        not shutil.which('git'),
        reason="test needs git to be installed"
)
```
to autoskip, much like eg the integration tests for `whoosh` are.

**Comment by alexfikl** [comment]
> I was just writing up a PR of my own that would've used

That looks more convenient. I'll change it to use `shutil`!

**Comment by hseg** [comment]
OK, all tests pass on 0.14 + this, am packaging it along with this patch.

**Comment by alexfikl** [comment]
> OK, all tests pass on 0.14 + this, am packaging it along with this patch.

Thanks for checking! In it goes :rocket:

**Pull request merged**
