### PR TITLE
Add flake8-quotes, flake8-bugbear and pep8-naming

### PR DESCRIPTION
**Pull request by alexfikl**
This adds a few more `flake8` checks that seem to do more good than harm + fixes all the issues that pop up.

@alejandrogallo What do you think? They mostly enforce some more consistency (e.g. with string quoting)

### CODE REVIEW

**Comment by alejandrogallo** [comment]
I'm all for consistency, I think it's good, I should update the documentation for developing, giving people easy and trivial instructions how to test the code before pushing and opening pull requests, I think this is quite unclear at the moment, I can work on this today.

**Comment by alexfikl** [comment]
> I'm all for consistency, I think it's good, I should update the documentation for developing, giving people easy and trivial instructions how to test the code before pushing and opening pull requests, I think this is quite unclear at the moment, I can work on this today.

Awesome! Definitely agree that adding some text for that would be very helpful.

**Comment by alexfikl** [comment]
I gave this another read and couldn't spot anything weird so, since the tests are passing, it's good to go from my end! 

Feel free to merge / squash it when you get a chance.

**Comment by alejandrogallo** [comment]
Awesome!

**Pull request merged**
