### PR TITLE
doc_folder_option handles multiple folders

### PR DESCRIPTION
**Pull request by Twix53791**
xref #626

### CODE REVIEW

**Comment by Twix53791** [comment]
1) Not sure about the changes in explore.py/cache.py/open.py (their structure was different...).

2) Question :  in cli.py need I to make theses changes? (and it is the good syntax, Optional[tuple[]] ?) 
```diff
def handle_doc_folder_or_query(
        query: str,
-        doc_folder: Optional[str]) -> List[papis.document.Document]:
+        doc_folder: Optional[Tuple[str, ...]]) -> List[papis.document.Document]:
...
def handle_doc_folder_query_sort(
        query: str,
-        doc_folder: Optional[str],
+        doc_folder: Optional[Tuple[str, ...]],
```

**Comment by alexfikl** [comment]
> 1. Not sure about the changes in explore.py/cache.py/open.py (their structure was different...).

* explore: just need to do a `[papis.document.from_folder(d) for d in doc_folder]` like you did in `cli.py`.
* cache-update: should be good to go with changes to `Tuple[str, ...]`.
* cache-add: you'll need to wrap the whole thing in a `for d in doc_folder` loop.
* cache-rm: same as cache-update.
* cache-update-newer: same as cache-update.
* open: should only need the change to `Tuple[str, ...]` as well?

Let me know if I missed anything.

> 2. Question :  in cli.py need I to make theses changes? (and it is the good syntax, Optional[tuple[]] ?

Yep, that's correct! 

>     3. I don't understand the tests failing errors : it says "error: Name "Tuple" is not defined Did you forget to import it from "typing"?", but in all theses files there is already `from typing import List, Dict, Tuple` ...

I just checked `addto.py` and it does not import `Tuple`. Maybe you missed some files in there?

**Comment by Twix53791** [comment]
OK.
 Are you sure about cache-rm/cache-update-newer ? Cache-add call `papis.document.from_folder`, which take a string as arg, so yes we need to loop through the doc_folder tuple. But cache-rm and cache-update-newer, like cache-update, call `papis.cli.handle_doc_folder_query_all_sort` and then after `for doc in documents:`. It already loop through the documents. 
??

**Comment by alexfikl** [comment]
> OK. Are you sure about cache-rm/cache-update-newer? Cache-add call `papis.document.from_folder`, which take a string as arg, so yes we need to loop through the doc_folder tuple. But cache-rm and cache-update-newer, like cache-update, call `papis.cli.handle_doc_folder_query_all_sort` and then after `for doc in documents:`. It already loop through the documents. ??

Not sure where we got confused, but your changes are absolutely correct!

I can't think of any other places that would need to be updated, so this looks good to go from my end. Did you want to make any other changes or is it ready to merge in? :grin:

**Comment by Twix53791** [comment]
I think its good like that! Thank you for your support :)

**Pull request merged**
