### PR TITLE
Stricter file download checks in crossref

### PR DESCRIPTION
**Pull request by alexfikl**
When running 
```
papis add --from doi '10.1007/s00607-002-1450-4'
```
the importer would get a `doc_url` of http://link.springer.com/article/10.1007/s00607-002-1450-4/fulltext.html, which would get redirected to the default paper page because of lack of access, and then download that as an html document.

I'm not sure disallowing redirects is the best way to handle that, since there are legitimate uses for them. What do you think?

### CODE REVIEW

**Comment by alejandrogallo** [comment]
Hmm so what happens if we disallow redirects, what do I get in this case?

**Comment by alexfikl** [comment]
> Hmm so what happens if we disallow redirects, what do I get in this case?

With this PR, it basically won't save any files resulting from a redirect, which doesn't sound like a great idea. 

The issue I was trying to fix is just to not have papis download html webpages when I don't have access to the actual paper. Maybe checking the file type of the downloaded document against a whitelist is better? What do you think?

**Comment by alexfikl** [comment]
Changed the importer to only save the files if
* the HTTP status code is `OK (200)`, but still allowing redirects
* the downloaded contents are recognizable by `filetype`, which excludes plaintext like html.

Does that sound more reasonable?

**Comment by alejandrogallo** [comment]
I think this is reasonable, let's roll with that for the time being.

**Comment by alexfikl** [comment]
> I think this is reasonable, let's roll with that for the time being.

Thanks! Feel free to ping me for a fix if it brakes people's workflow!

**Pull request merged**
