### PR TITLE
Fix doc generation

### PR DESCRIPTION
**Pull request by alexfikl**
Running with
```
make html SPHINXOPTS="-W --keep-going -n"
```
showed quite a few errors, which this should fix.

### CODE REVIEW

**Comment by alexfikl** [comment]
The online docs are current not quite right either. e.g. 
* commands: https://papis.readthedocs.io/en/latest/commands.html
* the default value for `status_line_format`: https://papis.readthedocs.io/en/latest/configuration.html#terminal-user-interface-picker

and probably others. Haven't checked everything, but this should improve it a bit.

**Comment by jghauser** [comment]
I was actually just starting to write down some thoughts on improving the docs. I think a more general overhaul would be useful (rewriting sections, re-organising sections, etc.). I'll start a discussion thread in the next days once I've thought about it a little. Just wanted to give you a heads up (not that it clashes with this PR in any way!).

**Comment by alexfikl** [comment]
> I was actually just starting to write down some thoughts on improving the docs. I think a more general overhaul would be useful (rewriting sections, re-organising sections, etc.). I'll start a discussion thread in the next days once I've thought about it a little. Just wanted to give you a heads up (not that it clashes with this PR in any way!).

That sounds great! I was having some similar thoughts while jumping around all the sections and fixing these small issues, so I'm happy to help out :rocket:

**Comment by alejandrogallo** [comment]
That would be great, there are some things that are also outdated, which would be super annoying for new users.
Please Alex feel free to merge this whenever you see fit.

**Pull request merged**
